# Generated by Django 3.1.7 on 2021-03-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_detailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('popular', 'Carro Popular'), ('luxury', 'Carro de Luxo'), ('sporting', 'Carro esportivo'), ('suv', 'SUV'), ('pickup', 'Caminhonete'), ('van_minivan', 'Van/MiniVan'), ('motorbike', 'Moto Comum'), ('sports_bike', 'Moto Esportiva'), ('other', 'Outro')], default='popular', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
